/* Fluxo fotográfico no navegador com NF-es e câmera sintéticas. Não usa serviços externos.
   Requer Playwright/Chromium. TRIAGEM_PLAYWRIGHT_MODULE e TRIAGEM_BROWSER_BIN são opcionais.
   TRIAGEM_CDP_PORT habilita inspeção com agent-browser; TRIAGEM_INSPECT=1 mantém a tela aberta. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.TRIAGEM_PLAYWRIGHT_MODULE||'playwright');
const root=path.join(__dirname,'../triagem-nfe-vercel'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),photos=fs.readFileSync(path.join(root,'photos.js'),'utf8');
const origin='https://triagem.test',outDir=process.env.TRIAGEM_TEST_OUTPUT||'/tmp/triagem-photos-test';fs.mkdirSync(outDir,{recursive:true});
let passed=0,browser,debugPage;
const test=async(name,fn)=>{await fn();passed++;console.log('OK',name);};
function key(num){let s='1426101111111100011155001'+String(num).padStart(9,'0')+'112345678';assert.equal(s.length,43);let sum=0,w=2;for(let i=42;i>=0;i--){sum+=Number(s[i])*w;w=w===9?2:w+1;}const r=sum%11;return s+(r<2?0:11-r);}
const key1=key(101),key2=key(102);
function xml(num){return `<?xml version="1.0"?><nfeProc xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00"><NFe><infNFe Id="NFe${key(num)}" versao="4.00"><ide><cUF>14</cUF><natOp>Venda</natOp><mod>55</mod><serie>1</serie><nNF>${num}</nNF><dhEmi>2026-10-03T12:00:00-04:00</dhEmi><tpNF>1</tpNF><idDest>1</idDest><tpEmis>1</tpEmis><tpAmb>1</tpAmb><finNFe>1</finNFe><indFinal>0</indFinal></ide><emit><CNPJ>11111111000111</CNPJ><xNome>Emitente de teste ${num}</xNome><enderEmit><xMun>Boa Vista</xMun><UF>RR</UF></enderEmit><IE>240000001</IE><CRT>3</CRT></emit><dest><CNPJ>22222222000122</CNPJ><xNome>Destinatário de teste</xNome><enderDest><xMun>Pacaraima</xMun><UF>RR</UF></enderDest><indIEDest>1</indIEDest><IE>240000002</IE></dest><det nItem="1"><prod><cProd>1</cProd><xProd>Mortadela</xProd><NCM>16010000</NCM><CFOP>5102</CFOP><uCom>UN</uCom><qCom>1</qCom><vUnCom>1000</vUnCom><vProd>1000</vProd></prod><imposto><ICMS><ICMS00><orig>0</orig><CST>00</CST><vBC>1000</vBC><pICMS>20</pICMS><vICMS>200</vICMS></ICMS00></ICMS></imposto></det><total><ICMSTot><vProd>1000</vProd><vBC>1000</vBC><vICMS>200</vICMS><vNF>1000</vNF></ICMSTot></total><transp><modFrete>9</modFrete></transp></infNFe></NFe><protNFe><infProt><dhRecbto>2026-10-03T12:00:01-04:00</dhRecbto><cStat>100</cStat><xMotivo>Autorizado</xMotivo><nProt>teste</nProt></infProt></protNFe></nfeProc>`;}
const input=num=>({name:`nf-${num}.xml`,mimeType:'application/xml',buffer:Buffer.from(xml(num))});
async function db(page,store='photos'){return page.evaluate(store=>new Promise((resolve,reject)=>{const r=indexedDB.open('triagem.fotos',1);r.onerror=()=>reject(r.error);r.onsuccess=()=>{const d=r.result,t=d.transaction(store,'readonly'),q=t.objectStore(store).getAll();q.onsuccess=()=>{const data=q.result.map(({originalBlob,stampedBlob,...m})=>({...m,originalSize:originalBlob?.size,stampedSize:stampedBlob?.size}));resolve(data);};t.oncomplete=()=>d.close();t.onerror=()=>reject(t.error);};}),store);}
async function waitCount(page,count){const deadline=Date.now()+10000;while(Date.now()<deadline){if((await db(page)).length===count)return;await page.waitForTimeout(50);}assert.equal((await db(page)).length,count,'quantidade de fotos persistidas');}
async function closeCamera(page){await page.locator('#photoClose').click();await page.waitForFunction(()=>!document.querySelector('#photoDialog').open);await page.waitForTimeout(150);}
async function openCamera(page,k){await page.locator(`#out [data-note-key="${k}"][data-photo-action="camera"]`).click();await page.locator('#photoCapture:not([disabled])').waitFor();}
async function noOverflow(page){assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
(async()=>{
 const args=['--no-sandbox','--no-zygote','--single-process','--in-process-gpu','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream'];
 if(process.env.TRIAGEM_CDP_PORT)args.push('--remote-debugging-port='+process.env.TRIAGEM_CDP_PORT);
 browser=await chromium.launch({executablePath:process.env.TRIAGEM_BROWSER_BIN||undefined,headless:true,args});
 const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true,geolocation:{latitude:4.4302,longitude:-61.1458,accuracy:15},permissions:['camera','geolocation']}),page=await context.newPage(),errors=[],requests=[];
 debugPage=page;page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 await context.route('**/*',r=>{const url=r.request().url();if(url===origin+'/')return r.fulfill({status:200,contentType:'text/html',body:html});if(url.startsWith(origin+'/photos.js'))return r.fulfill({status:200,contentType:'application/javascript',body:photos});if(url.startsWith(origin+'/api/consulta'))return r.fulfill({status:503,contentType:'application/json',body:'{"status":"erro","mensagem":"Indisponibilidade sintética"}'});return r.fulfill({status:200,body:''});});
 await page.goto(origin+'/');
 await test('XML manual mostra captura vinculada à chave correta',async()=>{await page.locator('#fXml').setInputFiles(input(101));await page.locator(`[data-photos-note="${key1}"]`).waitFor();assert.equal(await page.locator('#out [data-photo-action="camera"]').count(),1);await noOverflow(page);});
 await test('Câmera real da API (fonte sintética), GPS e horário de RR',async()=>{await openCamera(page,key1);await page.waitForFunction(()=>document.querySelector('#photoGPS').textContent.includes('4.430200'));await page.locator('#photoLocality').fill('Posto Fiscal Pacaraima / BR-174');await page.locator('#photoCapture').click();await waitCount(page,1);await page.waitForFunction(()=>document.querySelector('#photoMessage').textContent.includes('Foto salva'));const [r]=await db(page);assert.equal(r.noteKey,key1);assert.equal(r.note.nNF,'101');assert.equal(r.kind,'camera');assert.equal(r.timeZone,'America/Boa_Vista');assert.equal(r.localitySource,'informada');assert.equal(r.geo.status,'ok');assert.equal(r.geo.latitude,4.4302);assert.equal(r.geo.accuracy,15);assert(r.originalSize>0&&r.stampedSize>0);await page.locator('#photoDialog').screenshot({path:path.join(outDir,'camera-mobile.png')});await closeCamera(page);});
 await test('GPS negado aparece explicitamente, sem coordenadas fictícias',async()=>{await page.evaluate(()=>{window.realGeo=navigator.geolocation.getCurrentPosition.bind(navigator.geolocation);navigator.geolocation.getCurrentPosition=(_ok,bad)=>bad({code:1});});await openCamera(page,key1);await page.waitForFunction(()=>document.querySelector('#photoGPS').textContent.includes('permissão'));await page.locator('#photoCapture').click();await waitCount(page,2);const r=(await db(page)).find(r=>r.geo.status==='denied');assert(r);assert.equal(r.geo.latitude,undefined);assert.equal(r.noteKey,key1);await page.waitForFunction(()=>document.querySelector('#photoMessage').textContent.includes('Foto salva'));await closeCamera(page);await page.evaluate(()=>navigator.geolocation.getCurrentPosition=window.realGeo);});
 await test('Salvar em andamento não troca o vínculo quando outra NF-e é renderizada',async()=>{await openCamera(page,key1);await page.locator('#photoCapture').click();await page.evaluate(x=>{state.nfs=[parseNFe(x,'teste-102')];renderAll();},xml(102));await waitCount(page,3);assert((await db(page)).every(r=>r.noteKey===key1));await page.waitForFunction(()=>document.querySelector('#photoMessage').textContent.includes('Foto salva'));await closeCamera(page);});
 await test('Outra nota recebe somente as próprias fotos; anexo não atesta data original',async()=>{const data=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=800;c.height=500;const x=c.getContext('2d');x.fillStyle='#2c6a4b';x.fillRect(0,0,800,500);x.fillStyle='white';x.font='48px sans-serif';x.fillText('IMAGEM SINTÉTICA - NF 102',40,100);return c.toDataURL('image/png').split(',')[1];});const chooser=page.waitForEvent('filechooser');await page.locator(`#out [data-photo-action="attach"][data-note-key="${key2}"]`).click();await (await chooser).setFiles({name:'foto-sintetica.png',mimeType:'image/png',buffer:Buffer.from(data,'base64')});await waitCount(page,4);await page.locator('#out .photo-gallery-details > summary').click();await page.locator('#out .photo-card').waitFor();const r=(await db(page)).find(r=>r.noteKey===key2);assert.equal(r.kind,'attachment');assert((await page.locator('#out .photo-gallery').innerText()).includes('data original não atestada'));assert.equal(await page.locator('#out .photo-card').count(),1);});
 await test('Pacote ZIP contém original, marcação e vínculo/horário/GPS',async()=>{const download=page.waitForEvent('download');await page.locator('#out [data-photo-action="download"]').click();const d=await download;await d.saveAs(path.join(outDir,'registro.zip'));assert(d.suggestedFilename().startsWith('NF-e-102-'));const annotation=await page.evaluate(async()=>{const r=await new Promise(resolve=>{const q=indexedDB.open('triagem.fotos',1);q.onsuccess=()=>{const d=q.result,t=d.transaction('photos','readonly'),req=t.objectStore('photos').index('noteKey').getAll(document.querySelector('#out [data-photos-note]').dataset.photosNote);req.onsuccess=()=>resolve(req.result[0]);t.oncomplete=()=>d.close();};});return {base64:await new Promise(resolve=>{const f=new FileReader();f.onload=()=>resolve(f.result.split(',')[1]);f.readAsDataURL(r.stampedBlob);})};});fs.writeFileSync(path.join(outDir,'foto-com-registro.jpg'),Buffer.from(annotation.base64,'base64'));});
 await test('Sem upload de fotos ou envio de coordenadas a serviços externos',async()=>{assert(requests.every(url=>url===origin+'/'||url.startsWith(origin+'/photos.js')||url.startsWith('https://fonts.')||url.startsWith('https://cdn.jsdelivr.net/')));});
 await test('Recarga preserva fotos e o histórico abre a galeria mesmo com falha do XML',async()=>{await page.reload();await page.locator('#tabHistorico').click();await page.locator('#histLista .photo-history-count').filter({hasText:'3 fotos'}).waitFor();await page.locator('#histLista .hist-card').first().click();await page.locator('#histDetalhe .photo-gallery-details > summary').click();await page.locator('#histDetalhe .photo-card').first().waitFor();assert((await page.locator('#histDetalhe').innerText()).includes('Não consegui recuperar o XML'));assert.equal(await page.locator('#histDetalhe .photo-card').count(),3);await noOverflow(page);});
 await test('Limpar histórico mantém fotos acessíveis em Notas com fotos',async()=>{await page.locator('#bVoltarHist').click();page.once('dialog',d=>d.accept());await page.locator('#bLimparHist').click();assert.equal(await page.locator('#histLista .hist-card').count(),0);await page.locator('#bFotosSalvas').click();await page.locator('#savedPhotosBody .photo-card').first().waitFor();assert.equal(await page.locator('#savedPhotosBody .photo-saved-note').count(),2);assert.equal(await page.locator('#savedPhotosBody .photo-card').count(),4);await page.locator('#savedPhotosDialog').screenshot({path:path.join(outDir,'galeria-mobile.png')});await page.locator('#savedPhotosClose').click();});
 await test('Permissão de câmera negada mantém anexo disponível',async()=>{await page.locator('#tabTriagem').click();await page.locator('#fXml').setInputFiles(input(101));await page.evaluate(()=>{window.realCamera=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=()=>Promise.reject(new DOMException('Negado','NotAllowedError'));});await page.locator('#out [data-photo-action="camera"]').click();await page.waitForFunction(()=>document.querySelector('#photoMessage').textContent.includes('Câmera bloqueada'));assert(await page.locator('#photoCapture').isDisabled());assert(await page.locator('#photoAttach').isEnabled());await closeCamera(page);await page.evaluate(()=>navigator.mediaDevices.getUserMedia=window.realCamera);});
 await test('Câmera obtida depois do cancelamento é encerrada',async()=>{await page.evaluate(()=>navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>window.pendingCameraResolve=resolve));await page.locator('#out [data-photo-action="camera"]').click();await page.waitForFunction(()=>!!window.pendingCameraResolve);await closeCamera(page);await page.evaluate(async()=>{window.cancelledStream=await window.realCamera({video:true,audio:false});window.pendingCameraResolve(window.cancelledStream);navigator.mediaDevices.getUserMedia=window.realCamera;});await page.waitForFunction(()=>window.cancelledStream.getTracks().every(t=>t.readyState==='ended'));assert.equal((await db(page)).length,4);});
 await test('Quota excedida não informa sucesso nem cria registro incompleto',async()=>{await openCamera(page,key1);await page.evaluate(()=>{window.realAdd=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(...args){if(this.name==='photos')throw new DOMException('Sem espaço','QuotaExceededError');return window.realAdd.apply(this,args);};});await page.locator('#photoCapture').click();await page.waitForFunction(()=>document.querySelector('#photoMessage').textContent.includes('Sem espaço'));assert.equal((await db(page)).length,4);assert(!((await page.locator('#photoMessage').innerText()).includes('Foto salva')));await page.evaluate(()=>IDBObjectStore.prototype.add=window.realAdd);await closeCamera(page);});
 await test('Voltar e fechar a câmera encerram o vídeo',async()=>{await openCamera(page,key1);await page.evaluate(()=>window.backStream=document.querySelector('#photoVideo').srcObject);await page.goBack();await page.waitForFunction(()=>!document.querySelector('#photoDialog').open&&window.backStream.getTracks().every(t=>t.readyState==='ended'));});
 await test('Excluir uma foto atualiza contagem e mantém as demais notas',async()=>{await page.locator('#tabHistorico').click();await page.locator('#bFotosSalvas').click();await page.locator('#savedPhotosBody .photo-card').first().waitFor();const id=await page.locator('#savedPhotosBody [data-photo-action="delete"]').first().getAttribute('data-photo-id');const row=(await db(page)).find(r=>r.id===id),before=(await db(page,'notes')).find(n=>n.noteKey===row.noteKey).count;page.once('dialog',d=>d.accept());await page.locator('#savedPhotosBody [data-photo-action="delete"]').first().click();await waitCount(page,3);await page.waitForFunction(()=>document.querySelectorAll('#savedPhotosBody .photo-card').length===3);assert.equal((await db(page,'notes')).find(n=>n.noteKey===row.noteKey)?.count||0,before-1);await page.locator('#savedPhotosClose').click();});
 await test('Layouts mobile/desktop, tema claro/escuro e ausência de erros',async()=>{await page.locator('#tabTriagem').click();for(const width of [390,1280]){await page.setViewportSize({width,height:844});for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);await noOverflow(page);await page.locator('#out .photo-box').screenshot({path:path.join(outDir,`fotos-${width}-${theme}.png`)});}}await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await openCamera(page,key1);await page.locator('#photoDialog').screenshot({path:path.join(outDir,'camera-dark.png')});assert(await page.evaluate(()=>document.querySelector('#photoDialog').scrollWidth<=document.querySelector('#photoDialog').clientWidth+1));await closeCamera(page);assert.deepEqual(errors,[]);});

 await test('Transação abortada não cria foto nem informa sucesso',async()=>{await openCamera(page,key1);await page.evaluate(()=>{window.realAdd=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(...args){const r=window.realAdd.apply(this,args);if(this.name==='photos')queueMicrotask(()=>this.transaction.abort());return r;};});await page.locator('#photoCapture').click();await page.waitForFunction(()=>document.querySelector('#photoMessage').textContent.includes('Não foi possível salvar'));assert.equal((await db(page)).length,3);await page.evaluate(()=>IDBObjectStore.prototype.add=window.realAdd);await closeCamera(page);});
 await test('Latitude/longitude zero são coordenadas válidas, não GPS ausente',async()=>{await page.evaluate(()=>navigator.geolocation.getCurrentPosition=ok=>ok({coords:{latitude:0,longitude:0,accuracy:20},timestamp:Date.now()}));await openCamera(page,key1);await page.waitForFunction(()=>document.querySelector('#photoGPS').textContent.includes('0.000000'));await page.locator('#photoCapture').click();await waitCount(page,4);const r=(await db(page)).find(r=>r.geo.latitude===0);assert.equal(r.geo.status,'ok');assert.equal(r.geo.longitude,0);await page.waitForFunction(()=>document.querySelector('#photoMessage').textContent.includes('Foto salva'));await closeCamera(page);});
 await test('Posição antiga não recebe indicação de GPS atual',async()=>{await page.evaluate(()=>navigator.geolocation.getCurrentPosition=ok=>ok({coords:{latitude:4.43,longitude:-61.14,accuracy:50},timestamp:Date.now()-120000}));await openCamera(page,key1);await page.waitForFunction(()=>document.querySelector('#photoGPS').textContent.includes('4.430000'));await page.locator('#photoCapture').click();await waitCount(page,5);assert((await db(page)).some(r=>r.geo.status==='stale'));await page.waitForFunction(()=>document.querySelector('#photoMessage').textContent.includes('Foto salva'));await closeCamera(page);await page.evaluate(()=>navigator.geolocation.getCurrentPosition=window.realGeo);});
 await test('Arquivo que não é imagem não cria registro',async()=>{const chooser=page.waitForEvent('filechooser');await page.locator('#out [data-photo-action="attach"]').click();await(await chooser).setFiles({name:'invalido.txt',mimeType:'text/plain',buffer:Buffer.from('texto')});await page.waitForFunction(()=>document.querySelector('#aviso').textContent.includes('Use uma imagem'));assert.equal((await db(page)).length,5);});
 console.log(`${passed} cenários fotográficos passaram. Artefatos: ${outDir}`);
 if(process.env.TRIAGEM_INSPECT==='1'){await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.documentElement.dataset.theme='light');await page.locator('#out [data-photo-action="camera"]').click();await page.locator('#photoCapture:not([disabled])').waitFor();console.log('INSPECT_READY');await new Promise(resolve=>{const timer=setInterval(()=>{if(fs.existsSync(path.join(outDir,'inspection.done'))){clearInterval(timer);resolve();}},250);});}
 await browser.close();
})().catch(async e=>{console.error(e);if(debugPage){fs.writeFileSync(path.join(outDir,'failure.html'),await debugPage.content().catch(()=>''));console.error(JSON.stringify(await db(debugPage).catch(()=>[])));await debugPage.screenshot({path:path.join(outDir,'failure.png')}).catch(()=>{});}if(browser)await browser.close().catch(()=>{});process.exitCode=1;});
